version: '3.9'
services:
  php-fpm-graphql:
    build: .
    image: "php-fpm-graphql"
    container_name: graphql-api
    volumes:
      - ./:/var/www/html
      - ./.config/docker/php/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./.config/docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./.config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:1.19.6
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
      - ./.config/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm-graphql
